### PR TITLE
Update plot_intres.pro

### PR DESCRIPTION
**Pull request by Amsoht**
-plot size default set to [1700,900]
-added height plot

what do you think? Instead, I could create an additional widget button like 'Plot sel. Substance [height]'.

### CODE REVIEW

**Review by FObersteiner — COMMENTED** [review]
Looks nice, I think it's cool to have both area and height on one plot! If you like, check out check_pobjects.pro (l.18 ff.) - I use dimensions relative to the screen resolution there. That's pretty nice if you have users with different screen settings. You want to implement that as well? Otherwise, we can merge this into `master`.

**Comment by Amsoht** [comment]
That's cool! what do you think of 
`dim = [screenSize[0]*0.95,screenSize[1]*0.85]`
or do you know of a full screen option? Fast googling couldn't get me an answer...

**Comment by FObersteiner** [comment]
I think the plot size is fine like you suggested. I've added a commit, let me know what you think of that ;-)

**Comment by Amsoht** [comment]
Yes I like it! I changed the bottom value of the margin, so the xlabel won't get cut off on my machine.

**Pull request merged**
